### ISSUE TITLE
highcharts component

### ISSUE THREAD

**Issue by WolfgangFahl** [zauberzeug/nicegui-highcharts#2]
This issue is for being referenced in the nicegui solutions bazaar

![grafik](https://github.com/zauberzeug/nicegui-highcharts/assets/1336221/2e850724-dcaa-4428-92e8-92ab39d198c9)

**Comment by falkoschindler** [comment]
See https://github.com/zauberzeug/nicegui-highcharts/pull/3#issuecomment-1865809359 about my concerns regarding intransparent issues and pull requests in NiceGUI project repositories.

**Comment by WolfgangFahl** [comment]
IMHO this small project is just a good test environment to get your feet wet and give feedback on the solution bazaar implementation - i aggree that the original discussion is a better place - i am closing this issue since it's already fullfilling it's purpose being a container to get a demo image url created by the github environment.

**Comment by WolfgangFahl** [comment]
http://ngdemo.bitplan.com/components/zauberzeug_nicegui-highcharts  now works
